id=id
pubts=pubts
product=product
product_cCode=product_cCode
productsku=productsku
productsku_cCode=productsku_cCode
qty=qty
subQty=subQty
unit=unit
stockUnitId=stockUnitId
invExchRate=invExchRate
unitExchangeType=unitExchangeType
batchno=batchno
producedate=producedate
invaliddate=invaliddate
goodsposition=goodsposition
materialOutsCharacteristics=materialOutsCharacteristics
materialOutsDefineCharacter=materialOutsDefineCharacter