product=cinventoryid
productsku=productsku
unit=unit
stockUnitId=stockUnitId
invExchRate=invExchRate
unitExchangeType=unitExchangeType
qty=noutnum
subQty=subQty
batchno=vbatchcode
id=id
pubts=pubts
othOutRecordsCharacteristics=othOutRecordsCharacteristics
othOutRecordsDefineCharacter=othOutRecordsDefineCharacter