code=invcode
name_name=invname
model_name=invtype
modelDescription_name=invspec
unitCode=meascode
unitName=measname
stockUnitCode=stockUnitCode
purchaseUnitCode=purchaseUnitCode
batchUnitCode=batchUnitCode
batchPriceUnitCode=batchPriceUnitCode
requireUnitCode=requireUnitCode
produceUnitCode=produceUnitCode
invExchRate=invExchRate
unitExchangeType=unitExchangeType
creator=creatorname
createTime=createtime
mnemonicCode=invmnecode
expiryDateManage=expiryDateManage
expireDateNo=expireDateNo
expireDateUnit=expireDateUnit
manageClassCode=matertype
deliveryWarehouseCode=storcode
id=id