id=po_id
code=scddh
productCode=inv_code
productName=inv_name
startDate=jhkgrq
finishDate=jhwgrq
quantity=jhwgsl
versionCode=bomver
bomId=bom_id
cgddh=zdy1
SC01=zdy3
customerName=zdy10
creator=zdr
createTime=zdrq
bodyid=bodyid
batchNo=pch
freeCharacteristics=freeCharacteristics